"""hreflang extractor + validator.

Pulls ``<link rel="alternate" hreflang="...">`` annotations from a page and runs
basic validity checks: x-default presence, self-reference, duplicate langs, and
obviously malformed language codes.
"""

from __future__ import annotations

import re

from seohead.recon.net import http_client
from seohead.sf.core.normalize import norm_url

_UA = "Mozilla/5.0 (compatible; SEOHEAD-Tools/3.0; +https://seohead.tech/seotools)"

# An hreflang value is a language tag: language, optionally a script, optionally
# a region, in that order and case-insensitive. A shape-only regex cannot decide
# validity — "xx" and "en-XQ" have the right shape and name nothing — so each
# subtag is checked against its register. The lists below are the codes ICU
# treats as canonical, minus the ones that name no real language, script or
# place: ZZ (unknown), QO (a macro-region), XA/XB (test pseudo-regions), the Z*
# script placeholders and Qaag. Deprecated aliases are excluded by construction,
# which is what rejects the classic "en-UK" (the country is GB).
ISO_639_1 = frozenset(
    (
        "aa",
        "ab",
        "ae",
        "af",
        "ak",
        "am",
        "an",
        "ar",
        "as",
        "av",
        "ay",
        "az",
        "ba",
        "be",
        "bg",
        "bh",
        "bi",
        "bm",
        "bn",
        "bo",
        "br",
        "bs",
        "ca",
        "ce",
        "ch",
        "co",
        "cr",
        "cs",
        "cu",
        "cv",
        "cy",
        "da",
        "de",
        "dv",
        "dz",
        "ee",
        "el",
        "en",
        "eo",
        "es",
        "et",
        "eu",
        "fa",
        "ff",
        "fi",
        "fj",
        "fo",
        "fr",
        "fy",
        "ga",
        "gd",
        "gl",
        "gn",
        "gu",
        "gv",
        "ha",
        "he",
        "hi",
        "ho",
        "hr",
        "ht",
        "hu",
        "hy",
        "hz",
        "ia",
        "id",
        "ie",
        "ig",
        "ii",
        "ik",
        "io",
        "is",
        "it",
        "iu",
        "ja",
        "jv",
        "ka",
        "kg",
        "ki",
        "kj",
        "kk",
        "kl",
        "km",
        "kn",
        "ko",
        "kr",
        "ks",
        "ku",
        "kv",
        "kw",
        "ky",
        "la",
        "lb",
        "lg",
        "li",
        "ln",
        "lo",
        "lt",
        "lu",
        "lv",
        "mg",
        "mh",
        "mi",
        "mk",
        "ml",
        "mn",
        "mr",
        "ms",
        "mt",
        "my",
        "na",
        "nb",
        "nd",
        "ne",
        "ng",
        "nl",
        "nn",
        "no",
        "nr",
        "nv",
        "ny",
        "oc",
        "oj",
        "om",
        "or",
        "os",
        "pa",
        "pi",
        "pl",
        "ps",
        "pt",
        "qu",
        "rm",
        "rn",
        "ro",
        "ru",
        "rw",
        "sa",
        "sc",
        "sd",
        "se",
        "sg",
        "si",
        "sk",
        "sl",
        "sm",
        "sn",
        "so",
        "sq",
        "sr",
        "ss",
        "st",
        "su",
        "sv",
        "sw",
        "ta",
        "te",
        "tg",
        "th",
        "ti",
        "tk",
        "tn",
        "to",
        "tr",
        "ts",
        "tt",
        "tw",
        "ty",
        "ug",
        "uk",
        "ur",
        "uz",
        "ve",
        "vi",
        "vo",
        "wa",
        "wo",
        "xh",
        "yi",
        "yo",
        "za",
        "zh",
        "zu",
    )
)

ISO_3166_1 = frozenset(
    (
        "AC",
        "AD",
        "AE",
        "AF",
        "AG",
        "AI",
        "AL",
        "AM",
        "AO",
        "AQ",
        "AR",
        "AS",
        "AT",
        "AU",
        "AW",
        "AX",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BJ",
        "BL",
        "BM",
        "BN",
        "BO",
        "BQ",
        "BR",
        "BS",
        "BT",
        "BV",
        "BW",
        "BY",
        "BZ",
        "CA",
        "CC",
        "CD",
        "CF",
        "CG",
        "CH",
        "CI",
        "CK",
        "CL",
        "CM",
        "CN",
        "CO",
        "CP",
        "CQ",
        "CR",
        "CU",
        "CV",
        "CW",
        "CX",
        "CY",
        "CZ",
        "DE",
        "DG",
        "DJ",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EA",
        "EC",
        "EE",
        "EG",
        "EH",
        "ER",
        "ES",
        "ET",
        "EU",
        "EZ",
        "FI",
        "FJ",
        "FK",
        "FM",
        "FO",
        "FR",
        "GA",
        "GB",
        "GD",
        "GE",
        "GF",
        "GG",
        "GH",
        "GI",
        "GL",
        "GM",
        "GN",
        "GP",
        "GQ",
        "GR",
        "GS",
        "GT",
        "GU",
        "GW",
        "GY",
        "HK",
        "HM",
        "HN",
        "HR",
        "HT",
        "HU",
        "IC",
        "ID",
        "IE",
        "IL",
        "IM",
        "IN",
        "IO",
        "IQ",
        "IR",
        "IS",
        "IT",
        "JE",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KP",
        "KR",
        "KW",
        "KY",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LI",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "LY",
        "MA",
        "MC",
        "MD",
        "ME",
        "MF",
        "MG",
        "MH",
        "MK",
        "ML",
        "MM",
        "MN",
        "MO",
        "MP",
        "MQ",
        "MR",
        "MS",
        "MT",
        "MU",
        "MV",
        "MW",
        "MX",
        "MY",
        "MZ",
        "NA",
        "NC",
        "NE",
        "NF",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NR",
        "NU",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PF",
        "PG",
        "PH",
        "PK",
        "PL",
        "PM",
        "PN",
        "PR",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RE",
        "RO",
        "RS",
        "RU",
        "RW",
        "SA",
        "SB",
        "SC",
        "SD",
        "SE",
        "SG",
        "SH",
        "SI",
        "SJ",
        "SK",
        "SL",
        "SM",
        "SN",
        "SO",
        "SR",
        "SS",
        "ST",
        "SV",
        "SX",
        "SY",
        "SZ",
        "TA",
        "TC",
        "TD",
        "TF",
        "TG",
        "TH",
        "TJ",
        "TK",
        "TL",
        "TM",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "UM",
        "UN",
        "US",
        "UY",
        "UZ",
        "VA",
        "VC",
        "VE",
        "VG",
        "VI",
        "VN",
        "VU",
        "WF",
        "WS",
        "XK",
        "YE",
        "YT",
        "ZA",
        "ZM",
        "ZW",
    )
)

ISO_15924 = frozenset(
    (
        "Adlm",
        "Afak",
        "Aghb",
        "Ahom",
        "Arab",
        "Aran",
        "Armi",
        "Armn",
        "Avst",
        "Bali",
        "Bamu",
        "Bass",
        "Batk",
        "Beng",
        "Berf",
        "Bhks",
        "Blis",
        "Bopo",
        "Brah",
        "Brai",
        "Bugi",
        "Buhd",
        "Cakm",
        "Cans",
        "Cari",
        "Cham",
        "Cher",
        "Chrs",
        "Cirt",
        "Copt",
        "Cpmn",
        "Cprt",
        "Cyrl",
        "Cyrs",
        "Deva",
        "Diak",
        "Dogr",
        "Dsrt",
        "Dupl",
        "Egyd",
        "Egyh",
        "Egyp",
        "Elba",
        "Elym",
        "Ethi",
        "Gara",
        "Geok",
        "Geor",
        "Glag",
        "Gong",
        "Gonm",
        "Goth",
        "Gran",
        "Grek",
        "Gujr",
        "Gukh",
        "Guru",
        "Hanb",
        "Hang",
        "Hani",
        "Hano",
        "Hans",
        "Hant",
        "Hatr",
        "Hebr",
        "Hira",
        "Hluw",
        "Hmng",
        "Hmnp",
        "Hrkt",
        "Hung",
        "Inds",
        "Ital",
        "Jamo",
        "Java",
        "Jpan",
        "Jurc",
        "Kali",
        "Kana",
        "Kawi",
        "Khar",
        "Khmr",
        "Khoj",
        "Kits",
        "Knda",
        "Kore",
        "Kpel",
        "Krai",
        "Kthi",
        "Lana",
        "Laoo",
        "Latf",
        "Latg",
        "Latn",
        "Lepc",
        "Limb",
        "Lina",
        "Linb",
        "Lisu",
        "Loma",
        "Lyci",
        "Lydi",
        "Mahj",
        "Maka",
        "Mand",
        "Mani",
        "Marc",
        "Maya",
        "Medf",
        "Mend",
        "Merc",
        "Mero",
        "Mlym",
        "Modi",
        "Mong",
        "Moon",
        "Mroo",
        "Mtei",
        "Mult",
        "Mymr",
        "Nagm",
        "Nand",
        "Narb",
        "Nbat",
        "Newa",
        "Nkgb",
        "Nkoo",
        "Nshu",
        "Ogam",
        "Olck",
        "Onao",
        "Orkh",
        "Orya",
        "Osge",
        "Osma",
        "Ougr",
        "Palm",
        "Pauc",
        "Perm",
        "Phag",
        "Phli",
        "Phlp",
        "Phlv",
        "Phnx",
        "Plrd",
        "Prti",
        "Rjng",
        "Rohg",
        "Roro",
        "Runr",
        "Samr",
        "Sara",
        "Sarb",
        "Saur",
        "Sgnw",
        "Shaw",
        "Shrd",
        "Sidd",
        "Sidt",
        "Sind",
        "Sinh",
        "Sogd",
        "Sogo",
        "Sora",
        "Soyo",
        "Sund",
        "Sunu",
        "Sylo",
        "Syrc",
        "Syre",
        "Syrj",
        "Syrn",
        "Tagb",
        "Takr",
        "Tale",
        "Talu",
        "Taml",
        "Tang",
        "Tavt",
        "Tayo",
        "Telu",
        "Teng",
        "Tfng",
        "Tglg",
        "Thaa",
        "Thai",
        "Tibt",
        "Tirh",
        "Tnsa",
        "Todr",
        "Tols",
        "Toto",
        "Tutg",
        "Ugar",
        "Vaii",
        "Visp",
        "Vith",
        "Wara",
        "Wcho",
        "Wole",
        "Xpeo",
        "Xsux",
        "Yezi",
        "Yiii",
    )
)

_REGION_M49_RE = re.compile(r"^[0-9]{3}$")


def extract_hreflang(html: str, base_url: str = "") -> list[dict]:
    """Pure extraction of hreflang alternates from HTML (no network)."""
    from urllib.parse import urljoin

    from bs4 import BeautifulSoup

    from seohead.tools.parser import document_base_url

    soup = BeautifulSoup(html, features="lxml")
    # Alternates are relative URLs like any other: resolve them from the base.
    resolve_from = document_base_url(soup, base_url) if base_url else ""
    out: list[dict] = []
    for link in soup.find_all("link"):
        rel = " ".join(link.get("rel", [])).lower() if link.get("rel") else ""
        hreflang = link.get("hreflang")
        if "alternate" in rel and hreflang:
            href = link.get("href", "")
            out.append(
                {
                    "hreflang": hreflang,
                    "href": urljoin(resolve_from, href) if resolve_from else href,
                }
            )
    return out


def code_error(value: str) -> str:
    """Return why an hreflang value is invalid, or "" when it is valid."""
    tag = (value or "").strip()
    if not tag:
        return "empty value"
    if tag.lower() == "x-default":
        return ""
    parts = tag.split("-")
    if len(parts) > 3:
        return "more subtags than language-script-region"
    language = parts[0].lower()
    if language not in ISO_639_1:
        return f"{parts[0]!r} is not an ISO 639-1 language code"
    rest = parts[1:]
    if rest and len(rest[0]) == 4:
        script = rest[0].capitalize()
        if script not in ISO_15924:
            return f"{rest[0]!r} is not an ISO 15924 script code"
        rest = rest[1:]
    if rest:
        region = rest[0]
        if _REGION_M49_RE.match(region):
            return ""
        if region.upper() not in ISO_3166_1:
            return f"{region!r} is not an ISO 3166-1 alpha-2 or UN M.49 region code"
        rest = rest[1:]
    if rest:
        return f"unexpected subtag {rest[0]!r}"
    return ""


def validate(alternates: list[dict], page_url: str = "") -> list[str]:
    issues: list[str] = []
    langs = [a["hreflang"] for a in alternates]
    if not alternates:
        return ["no hreflang annotations found"]
    for lang in langs:
        reason = code_error(lang)
        if reason:
            issues.append(f"malformed hreflang code: {lang!r} ({reason})")
    # Language tags are case-insensitive, so "en-US" and "en-us" are the same
    # annotation twice, not two annotations.
    folded = [lang.strip().lower() for lang in langs]
    for lang in sorted({lang for lang in folded if folded.count(lang) > 1}):
        issues.append(f"duplicate hreflang: {lang}")
    if "x-default" not in folded:
        issues.append("no x-default alternate")
    hrefs = {norm_url(a["href"]) for a in alternates}
    if page_url and norm_url(page_url) not in hrefs:
        issues.append("page does not self-reference in its hreflang set")
    return issues


def check_hreflang(url: str, timeout: float = 25.0) -> dict:
    try:
        client, _http2_capable = http_client(
            timeout, follow_redirects=True, headers={"User-Agent": _UA}
        )
        with client:
            resp = client.get(url)
    except Exception as exc:
        return {"ok": False, "url": url, "error": str(exc)}
    final_url = str(resp.url)
    if not 200 <= resp.status_code < 300:
        # An error page carries no hreflang, and "no hreflang annotations found"
        # is a statement about a page that was never served.
        return {
            "ok": False,
            "url": url,
            "final_url": final_url,
            "status_code": resp.status_code,
            "error": f"The page returned HTTP {resp.status_code}, so it has no annotations to check",
        }
    alternates = extract_hreflang(resp.text, final_url)
    return {
        "ok": True,
        "url": url,
        "final_url": final_url,
        "status_code": resp.status_code,
        "count": len(alternates),
        "alternates": alternates,
        "issues": validate(alternates, final_url),
    }


if __name__ == "__main__":
    html = (
        '<link rel="alternate" hreflang="ru" href="/ru">'
        '<link rel="alternate" hreflang="en-US" href="/en">'
        '<link rel="alternate" hreflang="x-default" href="/">'
    )
    alts = extract_hreflang(html, "https://x.tld")
    assert len(alts) == 3 and alts[0]["href"] == "https://x.tld/ru"
    assert validate(alts, "https://x.tld/ru") == []
    assert "no x-default alternate" in validate(alts[:1], "")
    print("OK: hreflang self-check passed")
